### ISSUE TITLE
[Bug]: 文档不全，好多基础组件都没有说明

### ISSUE THREAD

**Issue by oceanynh** [mousheng/Barda#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

不知道如何才能获取组件的所有可用属性和方法，只能一个个的试。比如input,除了初始化可以放{{}}来放变量，在js里根本没法设置，我试过input.text, input.setValue, input.value都不行。还有无法用类似this的方法获取当前组件，比如input的失焦事件我无法用this.value来获得或更改当前input的内容。还有其他好多好多

### Expected Behavior

希望能有详细的说明，谢谢

### Steps to reproduce

我感觉lowcoder.org也好像凉了

**Comment by mousheng** [comment]
1.文档我太忙了，实在没时间搞，你可以看一下https://majiang.co/docs先凑合一下
2.你说的input组件，代码能控制值的呀,代码提示里有该组件所有的属性和方法，左侧有该组件所有暴露的属性和值
![image](https://github.com/mousheng/lowcoder_CN/assets/45591985/07e6178e-42dc-457a-9a30-01be3ec9114e)
3.this指针是无效的，针对访问组件直接用组件名就好了
![image](https://github.com/mousheng/lowcoder_CN/assets/45591985/5d5ccc66-bfb4-4638-ac6f-e042f2035bfa)

**Comment by oceanynh** [comment]
多谢回复，刚开始使用，可能有很多都不习惯。我先多使用几天，然后记录一下遇到的问题，再集中一起向您请教，谢谢
