### ISSUE TITLE
[Bug]: calendar 有滚动条的时候错位

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="968" alt="Screen Shot 2023-09-14 at 21 10 39" src="https://github.com/mousheng/lowcoder_CN/assets/77186544/91a0c293-e0b7-4f7b-84c7-608e2410aa35">

### Expected Behavior

不该错位

### Steps to reproduce

把控件拖进画布。

**Comment by mousheng** [comment]
已修复
