### ISSUE TITLE
[Feat]:figma布局借鉴

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#31]
**Is your feature request related to a problem? Please describe.**
设计画布，不对称，画布横向空间不够，特别是在笔记本上
**Describe the solution you'd like**
借鉴figma的布局空间，把左侧边栏收起变成菜单，帮助变成float button
**Describe alternatives you've considered**

<img width="1280" alt="Screen Shot 2023-09-16 at 14 27 02" src="https://github.com/mousheng/lowcoder_CN/assets/77186544/0053613a-366a-419e-8735-30b6cad32dcb">
<img width="350" alt="Screen Shot 2023-09-16 at 14 27 24" src="https://github.com/mousheng/lowcoder_CN/assets/77186544/1fa48967-0986-4637-b349-e2aa7448876a">

**Comment by mousheng** [comment]
左侧菜单没有修改的计划，我觉得还是挺方便，至于笔记本显示不够，可以快捷键切换是否显示，快捷键ctrl+B

**Comment by chenshuichao** [comment]
不对称啊😄，
