### ISSUE TITLE
[Feat]:一致性

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#32]
**Is your feature request related to a problem? Please describe.**
设计一致性
**Describe the solution you'd like**
<img width="597" alt="Screen Shot 2023-09-16 at 14 56 36" src="https://github.com/mousheng/lowcoder_CN/assets/77186544/95641878-5f8a-485f-9ad3-88c2f044906a">

**Describe alternatives you've considered**
应该保持一致性，都使用icon

**Additional context**

包括变量那边也应该有一个icon

**Comment by mousheng** [comment]
好主意，就是调试烦的一笔

**Comment by mousheng** [comment]
已修改
