### ISSUE TITLE
[Feat]:ant design5.9组件同步

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#33]
**Is your feature request related to a problem? Please describe.**
1）当时ant design5还没有发布，支持QRCode使用的是第三方；
2）ant design5.9支持了新组件：floatbutton，colorpicker，QRCode，tour，app

**Describe the solution you'd like**
1）更换第三方组件为官方组件：QRCode
2）添加新的组件实现：floatbutton，colorpicker，tour，app

**Comment by mousheng** [comment]
已完成

**Comment by chenshuichao** [comment]
@mousheng ，floatbutton，tour这两个组件，后续会支持吗？

**Comment by mousheng** [comment]
@chenshuichao 悬浮按钮前几天已经加了，漫游这个还没想好怎么搞，以后有空再说
