### ISSUE TITLE
[Feat]:mobile支持的改进建议

### ISSUE THREAD

**Issue by chensce** [mousheng/Barda#34]
响应式设计，在国内的组件中支持的不够好，ant design和ant design mobile就是两套组件，分别支持pc屏幕，phone屏幕。
基于此，建议当画布选择pc分辨率时，使用ant design组件；当画布选择phone分辨率时，使用ant design mobile组件。
comps目录下面建pc目录和mobile目录。

**Comment by mousheng** [comment]
拆成两套组件工程量有点大，暂时还没这方面考虑，现在想先完善pc端的组件
