### ISSUE TITLE
[Feat]:使用lowcoder来开发lowcoder

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#36]
https://github.com/mousheng/lowcoder_CN/tree/lowcoder_CN/client/packages/lowcoder/src/ide
这个包下面包含了，CompPlayground的构想：
是不是可以完善起来，结合这个文档https://majiang.co/docs/develop-plugins
做到，通过ide来开发comp，在左边栏，加一个ide的icon，相当于启动lowcoder即启动ide，然后做到“ 使用lowcoder来开发lowcoder”

**Comment by mousheng** [comment]
兄弟，想法很好，但不太现实，如果原生团队开发还有可能，这是个半路夭折的项目，啥都没留下，所有东西都靠自己摸索，很多基本的东西都还没搞明白
