### ISSUE TITLE
[Bug]: form.setData 无效

### ISSUE THREAD

**Issue by oceanynh** [mousheng/Barda#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在使用表单控件的时候，修改或更新的时候是没问题的，form.data能读取。但是如何我想初始化表单数据或根据日期条件自动获取表单内容的时候，form.setData就失效了，我尝试过form.setData({})或form.setData(jsonData)或form.setData({id:'1234',name:'name'})也是一点反应都没有

### Expected Behavior

我用chrome开发者工具调试的时候，在
```javascript
setData(Ut, Vt) {
        const Wt = yr(yr({}, Vt != null ? Vt : this.children.initialData.getView()), Ut);
        return this.runMethodOfItems({
            name: "setValue",
            getParams: Kt=>{
                var Qt;
                const qt = ((Qt = Kt.children.comp.children.formDataKey) == null ? void 0 : Qt.getView()) || Kt.children.name.getView()
                  , Yt = Wt[qt];
                return Yt !== void 0 ? [Yt] : void 0
            }
        }, {
            name: "resetValue"
        }, {
            name: "clearValue"
        })
    }
``` 
发行setValue与控件input的方法SetValue不一致，不知道是不是这原因导致的

### Steps to reproduce

已经尝试过query.run

**Comment by mousheng** [comment]
你使用的是Lowcoder什么版本？是我仓库克隆下去最新版还是在 lowcoder.mousheng.top上的版本？ lowcoder.mousheng.top上不是最新的版本
![2](https://github.com/mousheng/lowcoder_CN/assets/45591985/1af46c2b-81cf-4e47-8147-05bb2003b76d)

**Comment by oceanynh** [comment]
https://hub.docker.com/r/moushengkoo/lowcoder_cn/tags
我拉的是latest，不太清楚是什么版本,26天前拉的，我再更新一下。看看会不会有什么变化

**Comment by oceanynh** [comment]
我完全按照您的操作，毫无反应
![rr](https://github.com/mousheng/lowcoder_CN/assets/36233447/f1712d24-1ba6-404b-b40a-4ac5ef440bc4)

**Comment by mousheng** [comment]
![image](https://github.com/mousheng/lowcoder_CN/assets/45591985/151f4763-93c2-4cf7-afd9-d99dc154d93c)
已修复的问题，docker镜像版本太低了，我重新推了，你重新拉一下就好了
