### ISSUE TITLE
关于form.setData()无效的问题的解决方法及后续

### ISSUE THREAD

**Issue by oceanynh** [mousheng/Barda#45]
![image](https://github.com/mousheng/lowcoder_CN/assets/45591985/151f4763-93c2-4cf7-afd9-d99dc154d93c)
已修复的问题，docker镜像版本太低了，我重新推了，你重新拉一下就好了

_Originally posted by @mousheng in https://github.com/mousheng/lowcoder_CN/issues/44#issuecomment-1743938282_

**Comment by oceanynh** [comment]
按照版主的要求我重新拉了一下镜像，简单测试了一下，结果发现还是一样。于是我尝试删除所有已存在镜像，甚至删除docker，初始化wsl，但是结果还是一样，我都怀疑是否是系统原因导致以至于想重新买一台电脑用于测试。最终我在另外一台使用中文系统的电脑上进行测试的时候发现可以通过了，这才明白原来是因为我的docker服务器是意大利文系统。为什么国际化连方法名都要翻译转换掉，这会带来很多问题。

**Comment by mousheng** [comment]
感谢测试
英文环境的setData问题已经找到了
主要是我自己在试的时候，对莫名其妙冒出的三个方法也是一头雾水，为了看着更直观就修改成了中文
