### ISSUE TITLE
[Feat]:希望选项卡组件能隐藏标签头，tabbedContainer can hide tag

### ISSUE THREAD

**Issue by wengad82** [mousheng/Barda#49]
**Is your feature request related to a problem? Please describe.**
目前选项卡组件没办法隐藏标签头，有时候需要将标签头隐藏掉

**Describe the solution you'd like**
希望选项卡组件可以设置隐藏页签头

**Describe alternatives you've considered**

**Additional context**

**Comment by mousheng** [comment]
已添加
