### ISSUE TITLE
[Feat]:希望能有个穿梭框组件 ，hope  a transfers widget

### ISSUE THREAD

**Issue by wengad82** [mousheng/Barda#50]
**Describe the solution you'd like**
希望能有个穿梭框组件，like this
![image](https://github.com/mousheng/lowcoder_CN/assets/19250813/5e387187-44dd-41dd-92f2-0994e6e78c05)

**Comment by oceanynh** [comment]
用state做数据源应该很好解决吧

**Comment by mousheng** [comment]
@oceanynh  @wengad82  教程都已经给你们啦，快试试从从tooljet_cn那边移植过来，这两天我在搞gantee，还有好几个大坑要填，没时间移植

**Comment by mousheng** [comment]
已添加
