### ISSUE TITLE
[Feat]第一次加载时太慢了，F12发现是index****.js拖累了，随便放一个组件，大小11M，加载了40秒，是不是需要优化一下 

### ISSUE THREAD

**Issue by cnsdytzy** [mousheng/Barda#53]
第一次加载时太慢了，F12发现是index****.js拖累了，随便放一个组件，大小11M，加载了40秒，是不是需要优化一下

**Comment by mousheng** [comment]
加载40秒可能是CDN未命中，主JS文件打包后大概3.4M，这在低代码平台中已经算比较优秀的了，CDN预热后加载应该一两秒就够了，基本上算秒加载了

**Comment by cnsdytzy** [comment]
我是用docker安装的，主js文件11.3M，加载用时28秒。
<img width="674" alt="截屏2023-10-15 05 53 08" src="https://github.com/mousheng/lowcoder_CN/assets/1064568/05bcd795-946f-4653-a9c0-2cfe970561c6">

**Comment by mousheng** [comment]
好的，我会面会检查一下nginx gzip没有生效的问题

**Comment by mousheng** [comment]
已优化
