### ISSUE TITLE
[Feat]:更新或添加了好多组件呀，是时候捣腾那个ide

### ISSUE THREAD

**Issue by chenshuichao** [mousheng/Barda#54]
授人以渔，不如授人以渔，可以专注于捣腾那个ide目录了，后续可以使用这个ide来开发ant mobile的组件。

**Comment by mousheng** [comment]
![image](https://github.com/mousheng/lowcoder_CN/assets/45591985/154b0175-0db9-4abc-b4bd-8a98d21de548)
让你失望了，ide主要作用是测试组件用的，等我重新推送新镜像后，可以选择组件->右上角查看文档 打开相应的组件介绍，里面有组件的示例，点击就能测试组件
如果你要开发组件，你可以查看 https://moushengkoo.gitee.io/lowcoder_cn/#/develop-plugins 的原官方方式，也可以用我现在用的方式https://moushengkoo.gitee.io/lowcoder_cn/#/developer/addComponent

**Comment by chenshuichao** [comment]
好吧，😄，进展还是挺快的啊。
