### ISSUE TITLE
[Bug]: 组件选中错误

### ISSUE THREAD

**Issue by tcfly** [mousheng/Barda#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

先选择图标组件，再选择其上面的组件，依然选中的是图标组件
评论、穿梭组件也有该问题
![image](https://github.com/mousheng/lowcoder_CN/assets/49434080/64989047-182e-4eb5-9efb-e72e72682a4f)

### Expected Behavior

组件选择互不影响

### Steps to reproduce

先选择图标组件，再选择其上面的组件，依然选中的是图标组件

### Environment

https://lowcoder.mousheng.top/

**Comment by mousheng** [comment]
感谢，已定位问题
