### ISSUE TITLE
这个支持出码么？

### ISSUE THREAD

**Issue by gxiaosong** [mousheng/Barda#58]

**Comment by mousheng** [comment]
出码是什么意思？是指导出可直接部署的源代码吗？ 这是不支持的，低代码平台基本上都不支持导出源代码

**Comment by gxiaosong** [comment]
> 出码是什么意思？是指导出可直接部署的源代码吗？ 这是不支持的，低代码平台基本上都不支持导出源代码

是的，类似阿里的低代码引擎，可以导出源码
