### ISSUE TITLE
[Feat]:希望能有steps步骤条组件

### ISSUE THREAD

**Issue by wengad82** [mousheng/Barda#59]
**Is your feature request related to a problem? Please describe.**
在做一些带步骤的交互时，目前不容易控制，希望能够有步骤条组件方便进行步骤控制
when create some apps,the process is steping.now we can't control the process,hope there has a steps widget,it can help us control the 
interactive between apps and operator .

**Describe the solution you'd like**
能够控制，是否严格按照步骤操作,或者随意步骤间切换

**Comment by mousheng** [comment]
已添加
