### ISSUE TITLE
[Feat]:通过tc-qrcode生成base64二维码示例

### ISSUE THREAD

**Issue by exqmjmz** [mousheng/Barda#65]
这是一个通过tc-qrcode生成base64二维码，给jspdf或图片组件调用生成二维码
系统中的qrcode组件，没办法获取到对应的图片地址或base64，导致无法在别的地方引用或导出，估采取引入tc-qrcode插件生成qrcode

tc-qrcode
项目地址：https://github.com/theajack/qrcode/blob/master/README.cn.md#tc-qrcode
库安装地址：https://cdn.jsdelivr.net/npm/tc-qrcode/tc-qrcode.min.js

复制库安装地址到后台设置，高级选项中安装
![image](https://github.com/mousheng/lowcoder_CN/assets/12406935/ca4a878c-ff5f-4a57-8f77-eb75319ea405)

demo:
```javascript
const qrcode = window.TCQrcode.encodeAsBase64('01HG0AE0B6KJ4S4G4JSAF04CKS')
return qrcode
```

返回内容，返回base64图片样式
![image](https://github.com/mousheng/lowcoder_CN/assets/12406935/6cc4600c-f250-4ffc-b72c-863f63e0db23)

系统图片组件引用
![image](https://github.com/mousheng/lowcoder_CN/assets/12406935/9450800d-f42e-4336-8049-96b1395af59b)

jspdf引用
![image](https://github.com/mousheng/lowcoder_CN/assets/12406935/cb3c8ad8-2aed-4f05-9e83-0955bed9401d)

**Comment by mousheng** [comment]
好想法，但是能不引入新库就不引入新库，我在想办法原生提供dataURL的方法，canvas渲染下已经搞定了，svg我再想想办法
