### ISSUE TITLE
[Bug]: <title> 图片编辑器加载失败

### ISSUE THREAD

**Issue by 0x01999857** [mousheng/Barda#70]
![5R ( O4~}6_1UMM8E$_2}@B](https://github.com/mousheng/lowcoder_CN/assets/92218055/2725420b-891f-46ca-b702-1376cd6ac7d4)

图片编辑器加载失败

### Expected Behavior

无

### Steps to reproduce

无

**Comment by mousheng** [comment]
我测试好像没问题，你浏览器内核版本是多少，是不是内核版本太低了
