### ISSUE TITLE
[Feat]:左侧导航菜单，能够支持点击收起隐藏（最小化）到左侧，再点击弹出（最大化）

### ISSUE THREAD

**Issue by frank-dkvan** [mousheng/Barda#75]
**Is your feature request related to a problem? Please describe.**

目前内置支持的创建导航菜单，不支持点击收起隐藏。目前主流系统都需要支持左侧导航菜单，可以点击收起隐藏，再点击弹出。

**Describe the solution you'd like**

左侧导航菜单，可以点击收起隐藏（最小化），再点击弹出（最大化）。

**Describe alternatives you've considered**

**Additional context**

**Comment by mousheng** [comment]
好主意！！！
