### ISSUE TITLE
[Bug]: 链接不可访问

### ISSUE THREAD

**Issue by c20liu** [mousheng/Barda#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

部署链接不可访问：https://[yun.mousheng.top](https://yun.mousheng.top/lowcoder/docker-compose.yml)/lowcoder/docker-compose.yml

### Expected Behavior

可以获取的到对应链接文件，建议将文件更新在项目库文件中

### Steps to reproduce

直接访问

**Comment by mousheng** [comment]
@c20liu 哦，我原来的域名到期了，你可以先使用 http://yun.yylx.work/lowcoder/docker-compose.yml 下载，因为修改项目要改非常多的东西，所以一直懒得以前的链接

**Comment by c20liu** [comment]
@mousheng 非常感谢，这个可以访问了 
另外您前面维护的tooljet cn项目的 https://yun.mousheng.top/tooljet/autoConfigure.sh 也不可访问了，可以同步再提供一个链接吗？谢谢

**Comment by mousheng** [comment]
tooljet我已没精力维护，原仓库的代码是很久之前了的，不过你要下载的话，就访问这个 http://yun.yylx.work/tooljet/autoConfigure.sh

**Comment by c20liu** [comment]
谢谢，都可以下载了
